//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 09:30:26 PM CET 
//

package com.dexter.labs.communication;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for payloadType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="payloadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account" type="{}accountType"/>
 *         &lt;element name="company" type="{}companyType"/>
 *         &lt;element name="configuration" type="{}configurationType"/>
 *         &lt;element name="order" type="{}orderType"/>
 *         &lt;element name="user" type="{}userType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payloadType", propOrder = { "account", "company",
		"configuration", "order", "user" })
public class PayloadType {

	@XmlElement(required = true)
	protected AccountType account;
	@XmlElement(required = true)
	protected CompanyType company;
	@XmlElement(required = true)
	protected ConfigurationType configuration;
	@XmlElement(required = true)
	protected OrderType order;
	@XmlElement(required = true)
	protected UserType user;

	/**
	 * Gets the value of the account property.
	 * 
	 * @return possible object is {@link AccountType }
	 * 
	 */
	public AccountType getAccount() {
		return account;
	}

	/**
	 * Sets the value of the account property.
	 * 
	 * @param value
	 *            allowed object is {@link AccountType }
	 * 
	 */
	public void setAccount(AccountType value) {
		this.account = value;
	}

	/**
	 * Gets the value of the company property.
	 * 
	 * @return possible object is {@link CompanyType }
	 * 
	 */
	public CompanyType getCompany() {
		return company;
	}

	/**
	 * Sets the value of the company property.
	 * 
	 * @param value
	 *            allowed object is {@link CompanyType }
	 * 
	 */
	public void setCompany(CompanyType value) {
		this.company = value;
	}

	/**
	 * Gets the value of the configuration property.
	 * 
	 * @return possible object is {@link ConfigurationType }
	 * 
	 */
	public ConfigurationType getConfiguration() {
		return configuration;
	}

	/**
	 * Sets the value of the configuration property.
	 * 
	 * @param value
	 *            allowed object is {@link ConfigurationType }
	 * 
	 */
	public void setConfiguration(ConfigurationType value) {
		this.configuration = value;
	}

	/**
	 * Gets the value of the order property.
	 * 
	 * @return possible object is {@link OrderType }
	 * 
	 */
	public OrderType getOrder() {
		return order;
	}

	/**
	 * Sets the value of the order property.
	 * 
	 * @param value
	 *            allowed object is {@link OrderType }
	 * 
	 */
	public void setOrder(OrderType value) {
		this.order = value;
	}

	/**
	 * Gets the value of the user property.
	 * 
	 * @return possible object is {@link UserType }
	 * 
	 */
	public UserType getUser() {
		return user;
	}

	/**
	 * Sets the value of the user property.
	 * 
	 * @param value
	 *            allowed object is {@link UserType }
	 * 
	 */
	public void setUser(UserType value) {
		this.user = value;
	}

}
